# Generated by Django 5.2.4 on 2025-07-26 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('extracted_text', models.TextField()),
                ('overall_score', models.IntegerField()),
                ('structure_score', models.IntegerField()),
                ('grammar_score', models.IntegerField()),
                ('ats_score', models.IntegerField()),
                ('readability_score', models.IntegerField()),
                ('structure_analysis', models.JSONField()),
                ('grammar_analysis', models.JSONField()),
                ('ats_analysis', models.JSONField()),
                ('readability_analysis', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
